// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteBook.Data;

#nullable disable

namespace NoteBook.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240307224421_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("DataStorageApp.data.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is Post 1",
                            Title = "Post 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is Post 2",
                            Title = "Post 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "This is Post 3",
                            Title = "Post 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "This is Post 4",
                            Title = "Post 4"
                        },
                        new
                        {
                            Id = 5,
                            Content = "This is Post 5",
                            Title = "Post 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
